// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conv2D0_conv2D0_Pipeline_writeImg (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_out_0_address0,
        img_out_0_ce0,
        img_out_0_we0,
        img_out_0_d0,
        img_out_1_address0,
        img_out_1_ce0,
        img_out_1_we0,
        img_out_1_d0,
        img_outT_1_load7_reload,
        img_outT_0_load3_reload,
        img_outT_1_1_load15_reload,
        img_outT_0_1_load11_reload
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] img_out_0_address0;
output   img_out_0_ce0;
output   img_out_0_we0;
output  [7:0] img_out_0_d0;
output  [0:0] img_out_1_address0;
output   img_out_1_ce0;
output   img_out_1_we0;
output  [7:0] img_out_1_d0;
input  [7:0] img_outT_1_load7_reload;
input  [7:0] img_outT_0_load3_reload;
input  [7:0] img_outT_1_1_load15_reload;
input  [7:0] img_outT_0_1_load11_reload;

reg ap_idle;
reg img_out_0_ce0;
reg img_out_0_we0;
reg img_out_1_ce0;
reg img_out_1_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln40_fu_108_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln40_fu_132_p1;
wire   [0:0] trunc_ln40_fu_120_p1;
reg   [2:0] i_fu_46;
wire   [2:0] add_ln40_fu_114_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_1;
wire   [7:0] select_ln41_fu_154_p3;
wire   [0:0] tmp_fu_124_p3;
wire   [7:0] select_ln41_2_fu_146_p3;
wire   [7:0] select_ln41_1_fu_138_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_46 = 3'd0;
#0 ap_done_reg = 1'b0;
end

conv2D0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln40_fu_108_p2 == 1'd0)) begin
            i_fu_46 <= add_ln40_fu_114_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_46 <= 3'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln40_fu_108_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        img_out_0_ce0 = 1'b1;
    end else begin
        img_out_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln40_fu_120_p1 == 1'd0) & (icmp_ln40_fu_108_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        img_out_0_we0 = 1'b1;
    end else begin
        img_out_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        img_out_1_ce0 = 1'b1;
    end else begin
        img_out_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln40_fu_120_p1 == 1'd1) & (icmp_ln40_fu_108_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        img_out_1_we0 = 1'b1;
    end else begin
        img_out_1_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln40_fu_114_p2 = (ap_sig_allocacmp_i_1 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln40_fu_108_p2 = ((ap_sig_allocacmp_i_1 == 3'd4) ? 1'b1 : 1'b0);

assign img_out_0_address0 = zext_ln40_fu_132_p1;

assign img_out_0_d0 = select_ln41_fu_154_p3;

assign img_out_1_address0 = zext_ln40_fu_132_p1;

assign img_out_1_d0 = select_ln41_fu_154_p3;

assign select_ln41_1_fu_138_p3 = ((tmp_fu_124_p3[0:0] == 1'b1) ? img_outT_1_load7_reload : img_outT_0_load3_reload);

assign select_ln41_2_fu_146_p3 = ((tmp_fu_124_p3[0:0] == 1'b1) ? img_outT_1_1_load15_reload : img_outT_0_1_load11_reload);

assign select_ln41_fu_154_p3 = ((trunc_ln40_fu_120_p1[0:0] == 1'b1) ? select_ln41_2_fu_146_p3 : select_ln41_1_fu_138_p3);

assign tmp_fu_124_p3 = ap_sig_allocacmp_i_1[32'd1];

assign trunc_ln40_fu_120_p1 = ap_sig_allocacmp_i_1[0:0];

assign zext_ln40_fu_132_p1 = tmp_fu_124_p3;

endmodule //conv2D0_conv2D0_Pipeline_writeImg
